# Generated by Django 3.1.7 on 2022-01-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0002_remove_jobprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='binary_data',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='status',
        ),
    ]
